#ifndef	_VS_CONST_H
#define	_VS_CONST_H

#if defined(_PS3)
	#define shaderConstant uniform
#else
	#define shaderConstant const
#endif

#if !defined(_PS3)
#define gDLightDir gDLight.Dir
#endif

//	***********************************************************
#include	"VS_Config.h"
//	***********************************************************
//	*** CONSTANT MAPPING
//	***********************************************************
#define	C_VP_CONTEXT				0
#define	VIEWPORT_HALF_SIZE		c[C_VP_CONTEXT].xy
#define	VIEWPORT_HALF_SIZEX		c[C_VP_CONTEXT].x
#define	VIEWPORT_HALF_SIZEY		c[C_VP_CONTEXT].y
#define	INV_RDR_SIZE			c[C_VP_CONTEXT].zw
#define	VIEWPORT_RDR_CENTER		c[C_VP_CONTEXT+1].xy
#define	INV_DIST_FADE			c[C_VP_CONTEXT+1].z
//#define	c[C_VP_CONTEXT+1].w
#define	EYE_WORLD				c[C_VP_CONTEXT+2]
#define	CAM_WUP					c[C_VP_CONTEXT+3]
#define	CAM_WSIDE				c[C_VP_CONTEXT+4]
#define	C_VP_CONTEXT_END			5

#define	C_SCATTERING_CONTEXT			C_VP_CONTEXT_END
#define	C_SCATTERCONSTANTS1			c[C_SCATTERING_CONTEXT]
#define	C_SCATTERCONSTANTS2			c[C_SCATTERING_CONTEXT+1]
#define	C_TERM_MULTIPLIERS			c[C_SCATTERING_CONTEXT+2]
#define	C_BETA_1					c[C_SCATTERING_CONTEXT+3]
#define	C_BETA_DASH_1				c[C_SCATTERING_CONTEXT+4]
#define	C_BETA_2					c[C_SCATTERING_CONTEXT+5]
#define	C_BETA_DASH_2				c[C_SCATTERING_CONTEXT+6]
#define	C_BETA_1_PLUS_2				c[C_SCATTERING_CONTEXT+7]
#define	C_ONE_OVER_BETA_1_PLUS_2	c[C_SCATTERING_CONTEXT+8]	
#define	C_HG						c[C_SCATTERING_CONTEXT+9]

#define	C_SCATTERING_CONTEXT_END	C_SCATTERING_CONTEXT+10
#ifdef	_96_CONSTANTS
#define	C_SCATTERING_CONTEXT_END	C_SCATTERING_CONTEXT
#endif

#define	C_GROUND_CONTEXT			C_SCATTERING_CONTEXT_END
#define	C_GROUND_FADE_MIN			c[C_GROUND_CONTEXT].x
#define	C_GROUND_FADE_OVERMAXMIN	c[C_GROUND_CONTEXT].y
#define	C_GROUND_INVTEXSCALE		c[C_GROUND_CONTEXT].z
#define	C_GROUND_WINDX				c[C_GROUND_CONTEXT+1]
#define	C_GROUND_WINDZ				c[C_GROUND_CONTEXT+2]
#define	C_GROUND_CONTEXT_END		C_GROUND_CONTEXT+3

#ifdef	_96_CONSTANTS
#define	C_GROUND_CONTEXT_END		C_GROUND_CONTEXT
#endif


#define	C_VIEW_CONTEXT				C_GROUND_CONTEXT_END
#define VIEW_MAT				c[C_VIEW_CONTEXT]
#define	VIEW_TRANS				c[C_VIEW_CONTEXT+4]
#define	C_VIEW_CONTEXT_END			C_VIEW_CONTEXT+5

#define	C_PROJ_CONTEXT				C_VIEW_CONTEXT_END
#define PROJ_MAT				c[C_PROJ_CONTEXT]
#define	C_PROJ_CONTEXT_END			C_PROJ_CONTEXT+4

#define	C_WORLD_CONTEXT				C_PROJ_CONTEXT_END
#define WORLD_MAT				c[C_WORLD_CONTEXT]
#define	EYE_LOCAL				c[C_WORLD_CONTEXT+4]
#define	C_WORLD_CONTEXT_END			C_WORLD_CONTEXT+5

#define	C_SHADOWMAP_CONTEXT			C_WORLD_CONTEXT_END
#define	SHADOWMAP_MAT				c[C_SHADOWMAP_CONTEXT]
#define	SHADOWMAP_VIEWPOS			c[C_SHADOWMAP_CONTEXT+4]
#define	SHADOWMAP_VERTEX_BIAS		c[C_SHADOWMAP_CONTEXT+5].x
#define	SHADOWMAP_VERTEX_ADDBIAS	c[C_SHADOWMAP_CONTEXT+5].y
#define	SHADOWMAP_TEXTURE_SIZE		c[C_SHADOWMAP_CONTEXT+5].z
#define	SHADOWMAP_DONTUSE		c[C_SHADOWMAP_CONTEXT+5].w	
#define	C_SHADOWMAP_CONTEXT_END		C_SHADOWMAP_CONTEXT+6

#ifdef	_96_CONSTANTS
#define	C_SHADOWMAP_CONTEXT_END		C_SHADOWMAP_CONTEXT
#endif

// -- MATERIAL --
#define	C_MTL_CONTEXT				C_SHADOWMAP_CONTEXT_END
#define MTL_MAT					c[C_MTL_CONTEXT]
#define MTL_DIFFUSE				c[C_MTL_CONTEXT+2]
#define MTL_EMISSIVE			c[C_MTL_CONTEXT+3]
#define	MTL_OPACITY				c[C_MTL_CONTEXT+3].w
#define	MTL_SPECULAR			c[C_MTL_CONTEXT+4]
#define	MTL_SPECULAR_POW		c[C_MTL_CONTEXT+4].w
#define	MTL_PARAMS				c[C_MTL_CONTEXT+5]
#define	C_MTL_CONTEXT_END			C_MTL_CONTEXT+6

// -- DIR LIGHT &FOG --
#define	C_LIGHT_CONTEXT				C_MTL_CONTEXT_END
#define	GOURAUD_DFLT			c[C_LIGHT_CONTEXT]
#define	DLIGHT_DIR				c[C_LIGHT_CONTEXT+1]
#define	DLIGHT_RADSPECULAR		c[C_LIGHT_CONTEXT+1].w
#define	DLIGHT_AMBIENT			c[C_LIGHT_CONTEXT+2]
#define	DLIGHT_COLOR			c[C_LIGHT_CONTEXT+3]
#define	DSKY_DIR				c[C_LIGHT_CONTEXT+4].xyz
#define	DSKY_COLOR				c[C_LIGHT_CONTEXT+5]
#define	C_LIGHT_CONTEXT_END			C_LIGHT_CONTEXT+6

#define	C_FOG_CONTEXT				C_LIGHT_CONTEXT_END
#define FOG_PLANE				c[C_FOG_CONTEXT]
#define	FOG_COLOR				c[C_FOG_CONTEXT+1].xyz
#define	FOG_ON					c[C_FOG_CONTEXT+1].w
#define	C_FOG_CONTEXT_END			(C_FOG_CONTEXT+2)

// -- OMNIS --
#ifdef	_96_CONSTANTS
#define	C_OMNI_SIZE				4	//Vire PROLMATEX et WORLDTOLOCAL
#else
#define	C_OMNI_SIZE				12
#endif

#define	C_OMNI_CONTEXT				C_FOG_CONTEXT+2
#define	OMNI_0_POS				c[C_OMNI_CONTEXT+0*C_OMNI_SIZE+0]
#define	OMNI_0_STARTSQR			c[C_OMNI_CONTEXT+0*C_OMNI_SIZE+0].w
#define	OMNI_0_DIR				c[C_OMNI_CONTEXT+0*C_OMNI_SIZE+1]
#define	OMNI_0_RADSPECULAR		c[C_OMNI_CONTEXT+0*C_OMNI_SIZE+1].w			//On Off in case of Radiosity Map
#define	OMNI_0_COLOR			c[C_OMNI_CONTEXT+0*C_OMNI_SIZE+2]
#define	OMNI_0_RADDIFFUSE		c[C_OMNI_CONTEXT+0*C_OMNI_SIZE+2].w			//On Off in case of Radiosity Map
#define	OMNI_0_ATT				c[C_OMNI_CONTEXT+0*C_OMNI_SIZE+3].x
#define	OMNI_0_CUTOFF0			c[C_OMNI_CONTEXT+0*C_OMNI_SIZE+3].y
#define	OMNI_0_CUTOFF1			c[C_OMNI_CONTEXT+0*C_OMNI_SIZE+3].z
#define	C_OMNI_0_PROJMATTEX		C_OMNI_CONTEXT+0*C_OMNI_SIZE+4			//Matrice Projection Texture
#define	C_OMNI_0_WORLDTOLOCAL	C_OMNI_CONTEXT+0*C_OMNI_SIZE+8			//World 2 Local

#define	OMNI_1_POS				c[C_OMNI_CONTEXT+1*C_OMNI_SIZE+0]
#define	OMNI_1_STARTSQR			c[C_OMNI_CONTEXT+1*C_OMNI_SIZE+0].w
#define	OMNI_1_DIR				c[C_OMNI_CONTEXT+1*C_OMNI_SIZE+1]
#define	OMNI_1_RADSPECULAR		c[C_OMNI_CONTEXT+1*C_OMNI_SIZE+1].w			//On Off in case of Radiosity Map
#define	OMNI_1_COLOR			c[C_OMNI_CONTEXT+1*C_OMNI_SIZE+2]
#define	OMNI_1_RADDIFFUSE		c[C_OMNI_CONTEXT+1*C_OMNI_SIZE+2].w			//On Off in case of Radiosity Map
#define	OMNI_1_ATT				c[C_OMNI_CONTEXT+1*C_OMNI_SIZE+3].x
#define	OMNI_1_CUTOFF0			c[C_OMNI_CONTEXT+1*C_OMNI_SIZE+3].y
#define	OMNI_1_CUTOFF1			c[C_OMNI_CONTEXT+1*C_OMNI_SIZE+3].z
#define	C_OMNI_1_PROJMATTEX		C_OMNI_CONTEXT+1*C_OMNI_SIZE+4
#define	C_OMNI_1_WORLDTOLOCAL	C_OMNI_CONTEXT+1*C_OMNI_SIZE+8			//World 2 Local

#define	OMNI_2_POS				c[C_OMNI_CONTEXT+2*C_OMNI_SIZE+0]
#define	OMNI_2_STARTSQR			c[C_OMNI_CONTEXT+2*C_OMNI_SIZE+0].w
#define	OMNI_2_DIR				c[C_OMNI_CONTEXT+2*C_OMNI_SIZE+1]
#define	OMNI_2_RADSPECULAR		c[C_OMNI_CONTEXT+2*C_OMNI_SIZE+1].w		//On Off in case of Radiosity Map
#define	OMNI_2_COLOR			c[C_OMNI_CONTEXT+2*C_OMNI_SIZE+2]
#define	OMNI_2_RADDIFFUSE		c[C_OMNI_CONTEXT+2*C_OMNI_SIZE+2].w		//On Off in case of Radiosity Map
#define	OMNI_2_ATT				c[C_OMNI_CONTEXT+2*C_OMNI_SIZE+3].x
#define	OMNI_2_CUTOFF0			c[C_OMNI_CONTEXT+2*C_OMNI_SIZE+3].y
#define	OMNI_2_CUTOFF1			c[C_OMNI_CONTEXT+2*C_OMNI_SIZE+3].z
#define	C_OMNI_2_PROJMATTEX		C_OMNI_CONTEXT+2*C_OMNI_SIZE+4
#define	C_OMNI_2_WORLDTOLOCAL	C_OMNI_CONTEXT+2*C_OMNI_SIZE+8

#define	OMNI_3_POS				c[C_OMNI_CONTEXT+3*C_OMNI_SIZE+0]
#define	OMNI_3_STARTSQR			c[C_OMNI_CONTEXT+3*C_OMNI_SIZE+0].w
#define	OMNI_3_DIR				c[C_OMNI_CONTEXT+3*C_OMNI_SIZE+1]
#define	OMNI_3_RADSPECULAR		c[C_OMNI_CONTEXT+3*C_OMNI_SIZE+1].w		//On Off in case of Radiosity Map
#define	OMNI_3_COLOR			c[C_OMNI_CONTEXT+3*C_OMNI_SIZE+2]
#define	OMNI_3_RADDIFFUSE		c[C_OMNI_CONTEXT+3*C_OMNI_SIZE+2].w		//On Off in case of Radiosity Map
#define	OMNI_3_ATT				c[C_OMNI_CONTEXT+3*C_OMNI_SIZE+3].x
#define	OMNI_3_CUTOFF0			c[C_OMNI_CONTEXT+3*C_OMNI_SIZE+3].y
#define	OMNI_3_CUTOFF1			c[C_OMNI_CONTEXT+3*C_OMNI_SIZE+3].z
#define	C_OMNI_3_PROJMATTEX		C_OMNI_CONTEXT+3*C_OMNI_SIZE+4
#define	C_OMNI_3_WORLDTOLOCAL	C_OMNI_CONTEXT+3*C_OMNI_SIZE+8

#define	OMNI_4_POS				c[C_OMNI_CONTEXT+4*C_OMNI_SIZE+0]
#define	OMNI_4_STARTSQR			c[C_OMNI_CONTEXT+4*C_OMNI_SIZE+0].w
#define	OMNI_4_DIR				c[C_OMNI_CONTEXT+4*C_OMNI_SIZE+1]
#define	OMNI_4_RADSPECULAR		c[C_OMNI_CONTEXT+4*C_OMNI_SIZE+1].w		//On Off in case of Radiosity Map
#define	OMNI_4_COLOR			c[C_OMNI_CONTEXT+4*C_OMNI_SIZE+2]
#define	OMNI_4_RADDIFFUSE		c[C_OMNI_CONTEXT+4*C_OMNI_SIZE+2].w		//On Off in case of Radiosity Map
#define	OMNI_4_ATT				c[C_OMNI_CONTEXT+4*C_OMNI_SIZE+3].x
#define	OMNI_4_CUTOFF0			c[C_OMNI_CONTEXT+4*C_OMNI_SIZE+3].y
#define	OMNI_4_CUTOFF1			c[C_OMNI_CONTEXT+4*C_OMNI_SIZE+3].z
#define	C_OMNI_4_PROJMATTEX		C_OMNI_CONTEXT+4*C_OMNI_SIZE+4
#define	C_OMNI_4_WORLDTOLOCAL	C_OMNI_CONTEXT+4*C_OMNI_SIZE+8

// -- VECTOR --
	#if	MAX_OMNI==3
#define	C_DEFAULT					C_OMNI_CONTEXT+C_OMNI_SIZE+C_OMNI_SIZE+C_OMNI_SIZE
	#else
#define	C_DEFAULT					C_OMNI_CONTEXT+C_OMNI_SIZE+C_OMNI_SIZE+C_OMNI_SIZE+C_OMNI_SIZE+C_OMNI_SIZE
	#endif

#define C_QUARTER				c[C_DEFAULT].x
#define C_DTIME					c[C_DEFAULT].y
#define C_DUM					c[C_DEFAULT].z
#define	C_3QUARTER				c[C_DEFAULT].w
#define	C_NULL					c[C_DEFAULT+1].x
#define C_HALF					c[C_DEFAULT+1].y
#define C_UNIT					c[C_DEFAULT+1].z
#define C_TWO					c[C_DEFAULT+1].w
#define	C_INV16					c[C_DEFAULT+2].x
#define C_INV256				c[C_DEFAULT+2].y
#define C_INV4096				c[C_DEFAULT+2].z
#define C_INV16384				c[C_DEFAULT+2].w
#define	C_RIGHT					c[C_DEFAULT+1].zxxx			// 1 0 0 0
#define	C_UP					c[C_DEFAULT+1].xzxx			// 0 1 0 0
#define	C_FRONT					c[C_DEFAULT+1].xxzx			// 0 0 1 0	
#define	C_DEFAULT_END				C_DEFAULT+3

#define C_USER_CONTEXT				C_DEFAULT_END
#define C_USER0					c[C_USER_CONTEXT]
#define C_USER1					c[C_USER_CONTEXT+1]
#define C_USER2					c[C_USER_CONTEXT+2]
#define C_USER3					c[C_USER_CONTEXT+3]
#define C_USER4					c[C_USER_CONTEXT+4]		
#define C_USER5					c[C_USER_CONTEXT+5]
#define C_USER6					c[C_USER_CONTEXT+6]
#define C_USER7					c[C_USER_CONTEXT+7]
#define C_USER_CONTEXT_END			C_USER_CONTEXT+8
#ifdef	_96_CONSTANTS
#define	C_USER_CONTEXT_END			C_USER_CONTEXT
#endif

//	***********************************************************
// --  C_SHARED_ARRAY0  de Constante qui se supperposent
#define	C_SHARED_ARRAY0				C_USER_CONTEXT_END
//	***********************************************************

// -- VISIBILITY QUERY --
#define	C_VIZQUERY_CONTEXT			C_SHARED_ARRAY0
#define	VIZQUERY_XYZ			c[C_VIZQUERY_CONTEXT]
#define	VIZQUERY_SIZE			c[C_VIZQUERY_CONTEXT].w
#define	VIZQUERY_RESULT			c[C_VIZQUERY_CONTEXT+1].x
#define	C_VIZQUERY_CONTEXT_END		C_VIZQUERY_CONTEXT+2

// -- MORPH --
#define	C_MORPH_CONTEXT				C_SHARED_ARRAY0
#define	C_MORPH_RATIO_0			c[C_MORPH_CONTEXT].xxx
#define	C_MORPH_RATIO_1			c[C_MORPH_CONTEXT].yyy
#define	C_MORPH_RATIO_2			c[C_MORPH_CONTEXT].zzz
#define	C_MORPH_RATIO_3			c[C_MORPH_CONTEXT].www
#define	C_MORPH_CONTEXT_END			C_MORPH_CONTEXT+1

#ifdef	_96_CONSTANTS
#define	C_MORPH_CONTEXT_END			C_MORPH_CONTEXT
#endif

// -- LONGUEUR D EXTRUSION DU VOLUME STENCIL
#define	C_VOLEXT_CONTEXT			C_MORPH_CONTEXT
#define	C_VOLEXT					c[C_VOLEXT_CONTEXT]
#define C_VOLEXT_LIGHTPOS			c[C_VOLEXT_CONTEXT+1].xyz
#define C_VOLEXT_LIGHTATT0			c[C_VOLEXT_CONTEXT+1].w
#define C_VOLEXT_LIGHTCOL			c[C_VOLEXT_CONTEXT+2].xyz
#define C_VOLEXT_LIGHTATT1			c[C_VOLEXT_CONTEXT+2].w
#define	C_VOLEXT_CONTEXT_END		C_VOLEXT_CONTEXT+3

//	***********************************************************
// --  C_SHARED_ARRAY1 apres  C_SHARED_ARRAY0
#define	C_SHARED_ARRAY1				C_VOLEXT_CONTEXT_END
//	***********************************************************

#define	C_TARGET_MORPH_CONTEXT		C_SHARED_ARRAY1
#define	C_TARGET_MORPH0			c[C_TARGET_MORPH_CONTEXT]
#define	C_TARGET_MORPH1			c[C_TARGET_MORPH_CONTEXT+1]
#define	C_TARGET_MORPH2			c[C_TARGET_MORPH_CONTEXT+2]
#define	C_TARGET_MORPH3			c[C_TARGET_MORPH_CONTEXT+3]
#define	C_TARGET_MORPH4			c[C_TARGET_MORPH_CONTEXT+4]
#define	C_TARGET_MORPH5			c[C_TARGET_MORPH_CONTEXT+5]
#define	C_TARGET_MORPH6			c[C_TARGET_MORPH_CONTEXT+6]
#define	C_TARGET_MORPH7			c[C_TARGET_MORPH_CONTEXT+7]
#define	C_TARGET_MORPH8			c[C_TARGET_MORPH_CONTEXT+8]
#define	C_TARGET_MORPH_CONTEXT_END			C_TARGET_MORPH_CONTEXT+9

// Patch Constant
#define	C_PATCH_CONSTANT			C_SHARED_ARRAY1
#define	PATCH_A0				c[C_PATCH_CONSTANT]
#define	PATCH_SIGN_X			c[C_PATCH_CONSTANT].w
#define	PATCH_A1				c[C_PATCH_CONSTANT+1]
#define	PATCH_SIGN_Y			c[C_PATCH_CONSTANT+1].w
#define	PATCH_A2				c[C_PATCH_CONSTANT+2]
#define	PATCH_SIZE				c[C_PATCH_CONSTANT+2].w
#define	PATCH_A3				c[C_PATCH_CONSTANT+3]
									
#define	PATCH_B0				c[C_PATCH_CONSTANT+4]
#define	PATCH_B1				c[C_PATCH_CONSTANT+5]
#define	PATCH_B2				c[C_PATCH_CONSTANT+6]
#define	PATCH_B3				c[C_PATCH_CONSTANT+7]
								
#define	PATCH_C0				c[C_PATCH_CONSTANT+8]
#define	PATCH_C1				c[C_PATCH_CONSTANT+9]
#define	PATCH_C2				c[C_PATCH_CONSTANT+10]
#define	PATCH_C3				c[C_PATCH_CONSTANT+11]
								
#define	PATCH_D0				c[C_PATCH_CONSTANT+12]
#define	PATCH_D1				c[C_PATCH_CONSTANT+13]
#define	PATCH_D2				c[C_PATCH_CONSTANT+14]
#define	PATCH_D3				c[C_PATCH_CONSTANT+15]

#define	PATCH_NORMAL0			c[C_PATCH_CONSTANT+16]		//NORMAL0
#define	PATCH_NORMAL1_S0		c[C_PATCH_CONSTANT+17]		//NORMAL1-NORMAL0
#define	PATCH_NORMAL2_A0_S1_S3	c[C_PATCH_CONSTANT+18]		//NORMAL2+NORMAL0-NORMAL1-NORMAL3
#define	PATCH_NORMAL3_S0		c[C_PATCH_CONSTANT+19]		//NORMAL3-NORMAL0

#define	PATCH_UV0				c[C_PATCH_CONSTANT+20]
#define	PATCH_UV1_S0			c[C_PATCH_CONSTANT+21]
#define	PATCH_UV2_A0_S1_S3		c[C_PATCH_CONSTANT+22]
#define	PATCH_UV3_S0			c[C_PATCH_CONSTANT+23]

#define	PATCH_TG0				c[C_PATCH_CONSTANT+24]
#define	PATCH_TG1_S0			c[C_PATCH_CONSTANT+25]
#define	PATCH_TG2_A0_S1_S3		c[C_PATCH_CONSTANT+26]
#define	PATCH_TG3_S0			c[C_PATCH_CONSTANT+27]

/*
#define	PATCH_COLOR0			c[C_PATCH_CONSTANT+20]
#define	PATCH_COLOR1_S0			c[C_PATCH_CONSTANT+21]
#define	PATCH_COLOR2_A0_S1_S3	c[C_PATCH_CONSTANT+22]
#define	PATCH_COLOR3_S0			c[C_PATCH_CONSTANT+23]
*/

#define	C_PATCH_SIZE_CONSTANT	(C_PATCH_CONSTANT+28-(C_PATCH_CONSTANT))

// Particles Heat
#define	C_PARTICLE_CONTEXT			C_SHARED_ARRAY1
#define	PARTICLE_CAM_X			c[C_PARTICLE_CONTEXT].xyz
#define	PARTICLE_COS			c[C_PARTICLE_CONTEXT].w
#define	PARTICLE_CAM_Y			c[C_PARTICLE_CONTEXT+1].xyz
#define	PARTICLE_SIN			c[C_PARTICLE_CONTEXT+1].w
#define	PARTICLE_POS			c[C_PARTICLE_CONTEXT+2].xyz
#define	PARTICLE_COEFF			c[C_PARTICLE_CONTEXT+2].w
#define	PARTICLE_COLOR			c[C_PARTICLE_CONTEXT+3].xyz
#define	PARTICLE_SCALE_XY		c[C_PARTICLE_CONTEXT+4].xy
#define C_PARTICLE_CONTEXT_END		C_PARTICLE_CONTEXT+5

// Flare Constant
#define	C_FLARE_CONTEXT				C_SHARED_ARRAY1
#define	FLARE_VECXY				c[C_FLARE_CONTEXT].xy
#define	FLARE_ALPHA_MUL			c[C_FLARE_CONTEXT].z
#define	FLARE_SIZE_MUL			c[C_FLARE_CONTEXT].w
#define	C_FLARE_CONTEXT_END			C_FLARE_CONTEXT+1

// RotShape Constant
#define	C_RSHAPE_CONTEXT			C_SHARED_ARRAY1
#define	RSHAPE_PIVOT			c[C_RSHAPE_CONTEXT]
#define	RSHAPE_UPLEFT			c[C_RSHAPE_CONTEXT+1].xyz
#define	RSHAPE_SCALE			c[C_RSHAPE_CONTEXT+1].w
#define	RSHAPE_DWRIGHT			c[C_RSHAPE_CONTEXT+2].xyz
#define	C_RSHAPE_CONTEXT_END		C_RSHAPE_CONTEXT+3

// HField
#define	C_HFIELD_CONTEXT			C_SHARED_ARRAY1
#define	HFIELD_ORGX				c[C_HFIELD_CONTEXT].x
#define	HFIELD_ORGZ				c[C_HFIELD_CONTEXT].y
//#define	HFIELD_GSIZE			c[C_HFIELD_CONTEXT].zzzz
#define	HFIELD_TSIZE			c[C_HFIELD_CONTEXT].wwww
#define	C_HFIELD_CONTEXT_END		C_HFIELD_CONTEXT+1

#define	C_LAYER_CONTEXT				C_HFIELD_CONTEXT_END
#define	C_LAYER_START			c[C_LAYER_CONTEXT].x
#define	C_LAYER_GSIZE			c[C_LAYER_CONTEXT].y
#define	C_LAYER_ATTENUATION		c[C_LAYER_CONTEXT].z
#define	C_LAYER_NOISE			c[C_LAYER_CONTEXT].w
#define	C_LAYER_VFOG			c[C_LAYER_CONTEXT+1].x
#define	C_LAYER_CONTEXT_END			C_LAYER_CONTEXT+2

// Blend Matrix Cache	(Care BLEND MATRIX CACHE USE C_PATCH_CONSTANT ARRAY till END)
#define	C_CACHE_MATRIX_0			C_SHARED_ARRAY1
#define	C_CACHE_A_MATRIX_SIZE	6
#define	CACHE_MATRIX_SIZE		(C_END_CONSTANT-(C_CACHE_MATRIX_0))/C_CACHE_A_MATRIX_SIZE

#endif
